{{ if .Values.deployConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range .Values.messages }}
  {{ .name }}: "{{ .message }}"
  {{- end }}
{{ end }}
